parameters:
    daps_ldap.ldap.admin.dn: cn=admin,dc=example,dc=com
    daps_ldap.ldap.admin.password: root
    daps_ldap.ldap.admin.enable: true
    daps_ldap.ldap.admin.host: ldap://example.com
    daps_ldap.ldap.admin.port: 389
    daps_ldap.ldap.admin.dn: uid
    daps_ldap.ldap.admin.username_suffic: dcexample,dc=com