parameters:
#    daps_ldap.example.class: Daps\LdapBundle\Example

services:
#    daps_ldap.example:
#        class: %daps_ldap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
